plugins {
    java
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

val fabricCompileStubs by sourceSets.creating
val fabric by sourceSets.creating {
    compileClasspath += fabricCompileStubs.output
}
val neoforge by sourceSets.creating
val bukkit by sourceSets.creating

// The stub supplies only the MinecraftServer type needed to compile Fabric API's lifecycle callback;
// it is deliberately excluded from the fixture jar, where the real Victus target owns that class.
tasks.named<JavaCompile>(fabricCompileStubs.compileJavaTaskName) {
    javaCompiler.set(javaToolchains.compilerFor { languageVersion.set(JavaLanguageVersion.of(25)) })
    options.release.set(25)
}

// Fabric API 26.2 targets Java 25 even though the dependency-free launcher foundation stays Java 21.
tasks.named<JavaCompile>(fabric.compileJavaTaskName) {
    dependsOn(tasks.named(fabricCompileStubs.compileJavaTaskName))
    javaCompiler.set(javaToolchains.compilerFor { languageVersion.set(JavaLanguageVersion.of(25)) })
    options.release.set(25)
}

for (sourceSet in listOf(neoforge, bukkit)) {
    tasks.named<JavaCompile>(sourceSet.compileJavaTaskName) {
        javaCompiler.set(javaToolchains.compilerFor { languageVersion.set(JavaLanguageVersion.of(25)) })
        options.release.set(25)
    }
}
tasks.named<JavaCompile>(neoforge.compileJavaTaskName) {
    dependsOn(":hybrid-neoforge:neoforgeReconstructPatchedGame")
}

dependencies {
    "fabricCompileOnly"("net.fabricmc:fabric-loader:0.19.3")
    "fabricCompileOnly"("net.fabricmc.fabric-api:fabric-api-base:2.0.4+ece063239e")
    "fabricCompileOnly"("net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7")
    "neoforgeCompileOnly"("net.neoforged.fancymodloader:loader:11.0.17")
    "neoforgeCompileOnly"("net.neoforged:neoforge:26.2.0.57:universal")
    "neoforgeCompileOnly"("net.neoforged:bus:8.0.5")
    "neoforgeCompileOnly"("net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7")
    // The named patched-game API is generated by the locked installer machinery under build/.
    val neoForgeGameJar = providers.gradleProperty("neoForgePatchedGameJar").orElse(
        rootProject.layout.projectDirectory.file(
            "hybrid-neoforge/build/neoforge/install/libraries/net/neoforged/minecraft-server-patched/26.2.0.57/minecraft-server-patched-26.2.0.57.jar"
        ).asFile.absolutePath
    )
    "neoforgeCompileOnly"(files(neoForgeGameJar))
    // Compile the fixture against Paper's published API instead of the generated :victus-api
    // project output. A fresh clone has no hydrated paper-api sources until patch application,
    // while the fixture only needs the stable JavaPlugin contract.
    "bukkitCompileOnly"("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
}

// Fixtures compile against the real loader/plugin entrypoint APIs but contain only owned source and metadata.

val fabricFixtureJar by tasks.registering(Jar::class) {
    group = "build"
    archiveBaseName.set("victus-fixture-fabric")
    from(fabric.output)
}

val neoForgeFixtureJar by tasks.registering(Jar::class) {
    group = "build"
    archiveBaseName.set("victus-fixture-neoforge")
    from(neoforge.output)
}

val bukkitFixtureJar by tasks.registering(Jar::class) {
    group = "build"
    archiveBaseName.set("victus-fixture-bukkit")
    from(bukkit.output)
}

val fixtureArtifacts by tasks.registering {
    group = "build"
    description = "Builds owned Fabric, NeoForge, and Bukkit marker fixtures."
    dependsOn(fabricFixtureJar, neoForgeFixtureJar, bukkitFixtureJar)
}

val fixtureSelfTest by tasks.registering(JavaExec::class) {
    group = "verification"
    dependsOn(tasks.named("testClasses"), fixtureArtifacts)
    classpath = sourceSets.test.get().runtimeClasspath
    mainClass.set("cloud.victus.hybrid.fixtures.HybridFixturesSelfTest")
    args(layout.buildDirectory.dir("libs").get().asFile.absolutePath)
}

tasks.named("test") {
    dependsOn(fixtureSelfTest)
}
